config/routes.rb
Rails.application.routes.draw do
  get 'links/index'

  get 'instructions/index'

  get 'about/index'

  get 'home/index'

  # devise_for :users

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # devise_for :admins, path: 'admin', skip: :registrations
  root to: "home#index"
  resources :about
  resources :days
  resources :activities
  resources :users
  resources :instructions
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :day
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :activities
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :days
  has_many :activities, through: :days
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = Activity.where(user_id: current_user.id)
    puts current_user.id
    total = 0
    @activities.each do |activity|
      total += activity.points.to_i
    end
    @total = total
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def new
    @activity = Activity.new
    @user_id = current_user.id
  end

  def create
    puts current_user.id
    @user_id = current_user.id
    # @day_id = current_user.date.id
    @activity = Activity.new(activity_params)
      if @activity.save
        redirect_to days_path
      else
        puts "activity not saved!"
        redirect_to "/"
      end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])
    if @activity.update_attributes(activity_params)
      redirect_to days_path
    else
      render :edit
    end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to days_path
  end

private
  def activity_params
    params.require(:activity).permit(:actname, :points, :day_id, :user_id, :created_at, :updated_at)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_user
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :authenticate_user!
  def index
    @days = Day.where(user_id: current_user.id).order("date ASC").all
    puts current_user.id
  end


  def show
    @day = Day.find(params[:id])
    # @activity = Activity.where(user_id: current_user.id)
    #   if @activity.day_id == @day.id
    #       @name = @activity.actname
    #       @points = @activity.points
    #   end
    @activities = @day.activities
    total = 0
    @activities.each do |activity|
      total += activity.points.to_i
    end
    @total = total
  end


  def new
    @day = Day.new
    @user_id = current_user.id
  end

  def create
    puts current_user.id
    @user_id = current_user.id
    @day = Day.new(day_params)
      if @day.save
        redirect_to days_path
      else
        puts "not saved!"
        redirect_to "/"
      end

  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    @day = Day.find(params[:id])
    if @day.update_attributes(day_params)
      redirect_to days_path
    else
      render :edit
    end
  end

  def destroy
    @day = Day.find(params[:id])
    @day.destroy
    redirect_to days_path
  end

private
  def day_params
    params.require(:day).permit(:date, :journal, :user_id)
  end

  def activity_params
    params.require(:activity).permit(:actname, :points, :day_id, :user_id, :created_at, :updated_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/about/index.html.erb
<div class="index">
  <h1>About this app</h1>
  <div id="about">
    <h4>Everyone who suffers from depression knows that getting up and doing activities can make you feel better, but it's hard to find the inspiration to do so when you're really suffering.</h4>
    <h4>I created this app because it was something I would have found useful on my worst days.</h4>
    <h4>I'm not a doctor. I'm not a mental health professional. This app is something I created as a tool to inspire myself and to better communicate with my therapist. </h4>
    <h4>THIS APP IS NOT A SUBSTITUTE FOR THERAPY. </h4>
    <h4>I urge you to seek professional help if you're suffering.</h4>
    <a href = "https://www.psychologytoday.com/us/therapists">Here is one place you could start.</a>
  </div>
</div>

app/views/activities/_activity.html.erb
<div>
  <ul>
    <% @activities.each do |activity| %>
      <li>
        <%= link_to activity.actname, activity_path(activity) %>
        <%= activity.points %>
      </li>
      <% end %>
   </ul>
 </div>

app/views/activities/edit.html.erb
<div class="edit">
<%= form_for @activity do |f| %>
  <%= f.text_field :actname, placeholder: "Activity" %>
  <%= f.number_field :points, placeholder: "Points" %>
  <%= f.collection_select(:day_id, Day.all, :id, :date ) %>
  <%= f.submit "Add update!"%>
<% end %>
</div>

app/views/activities/index.html.erb
<div class = 'index'>
<h2>
  Today's Wins!
</h2>
</div>


<div class = 'index'>

    <ul>
      <% @activities.each do |activity| %>
        <li>
          <%= link_to activity.actname, activity_path(activity) %>
          <%= activity.points %>
        </li>
        <% end %>
    </ul>




<h2>Total points: <%= @total %> </h2>

</div>

<div class = 'index'>
<%= link_to "Add an Accomplishment", new_activity_path %>
</div>

app/views/activities/new.html.erb
<div class="new">
<%= form_for @activity do |f| %>
  <%= f.text_field :actname, placeholder: "Activity" %>
  <%= f.number_field :points, placeholder: "Points" %>
  <%= f.collection_select(:day_id, Day.where(user_id: current_user.id), :id, :date ) %>
  <%= f.hidden_field :user_id, value: @user_id %>
  <%= f.submit "Add 'em to the log!"%>
<% end %>
</div>

app/views/activities/show.html.erb
<div class = "show">

  <h1>
    <%= @activity.actname %>
  </h1>

  <h1>
    <%= @activity.points %> points
  </h1>



<%= link_to "Edit this accomplishment?", edit_activity_path(@activity) %>

<%= form_for @activity, html: {method: "delete"} do |f| %>
   <%= f.submit "Delete this accomplishment?" %>
<% end %>


<%= link_to 'Back to list', activity_path %>
</div>

app/views/application/_activity.html.erb
<div>
  <ul>
    <%= activity %>
   </ul>
 </div>

app/views/days/_activity.html.erb
<div>
  <ul>
    <% @activities.each do |activity| %>
      <li>
        <%= link_to activity.actname, activity_path(activity) %>
        <%= activity.points %>
      </li>
      <% end %>
   </ul>
 </div>

app/views/days/edit.html.erb
<div class="edit">
<%= form_for @day do |f| %>
  <%= f.date_field :date, placeholder: "Date" %>
  <%= f.text_field :journal, placeholder: "Reflections" %>
  <%= f.submit "Submit Changes"%>
<% end %>
</div>

app/views/days/index.html.erb
<div class = 'index'>
<h2>
  Daily Journal
</h2>

<div id="days">
<ul>
  <% @days.each do |day| %>
    <li>
      <%= link_to day.date.strftime("%d %B %Y"), day_path(day) %>
      <%= day.journal %>
    </li>
  <% end %>
</ul>
</div>

<a class="btn btn-primary btn-lg" href="/days/new" role="button">Add New Day &raquo;</a></p>

</div>

app/views/days/new.html.erb
<div class="new">
<%= form_for @day do |f| %>
  <%= f.date_field :date, placeholder: "Date" %>
  <%= f.text_field :journal, placeholder: "Reflections" %>
  <%= f.hidden_field :user_id, value: @user_id %>
  <%= f.submit "Add This Day"%>
<% end %>
</div>

app/views/days/show.html.erb
<div class = "show">
  <h1>
    <%= @day.date.strftime("%d %B %Y") %>
  </h1>

  <p id = "journal">
    <%= @day.journal %>
  </p>

  <div class="daily">
    <% @activities.each do |activity| %>
      Accomplishment: <%= activity.actname %><br />
      Points: <%= activity.points %><br />
      <a class="btn btn-primary btn-sm" href="/activities/<%= activity.id %>/edit" role="button">Edit &raquo;</a></p>
    <% end %>
  </div>

  <h2>Total points: <%= @total %> </h2>


<a class="btn btn-primary btn-lg" href="/activities/new" role="button">Add Accomplishment &raquo;</a></p>
<a class="btn btn-primary btn-md" href="/days/<%= @day.id %>/edit" role="button">Edit journal &raquo;</a></p>


  <%= form_for @day, html: {method: "delete"} do |f| %>
     <%= f.submit "Delete this day?" %>
  <% end %>


  <%= link_to 'Back to list', days_path %>

</div>

app/views/instructions/index.html.erb
<div class="index">
  <h1>How to use this app</h1>
  <h4>Once you're logged in, you can track information about your days.</h4>
  <h4>To start, click "New Day." Select a day from the calendar, and feel free to enter notes in the accompanying field - you can always edit them later.</h4>
  <h4>Enter in anything you did today that felt like a win - no matter how small!</h4>
  <h4>For example, I might enter, "Showered - 5 points" or "Exercised - 30 points" or "Called a friend - 20 points"</h4>
  <h4>There is no right or wrong amount of points for a day. Everything you do is better than nothing!</h4>
</div>

app/views/layouts/_footer.html.erb
      <footer class="navbar navbar-fixed-bottom">
        <div class="inner">
          <p>Disclaimer: This is not a substitute for mental health care. Please seek professional help if you think you might be depressed.</p>
          <p>Made with &#9829 by Emily Marro</p>
          <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
        </div>
      </footer>

app/views/layouts/_jumbotron.html.erb
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Everything is Progress</h1>
          <p>Keep track of all the things you do to feel better.</p>
          <p><a class="btn btn-primary btn-lg" href="/about" role="button">About this app &raquo;</a>
          <a class="btn btn-primary btn-lg" href="/instructions" role="button">Instructions &raquo;</a></p>
        </div>
      </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li class="navbar-brand"><%= link_to 'Home', days_path %></li>
    </div>
  <!--   <div class="collapse navbar-collapse" id="navbar-collapse"> -->
      <div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <!--This block is only visible to signed in users -->
          <li><%= link_to 'New Day', new_day_path %></li>
          <li><%= link_to 'New Activity', new_activity_path %></li>
          <li><%= link_to 'My Account', edit_user_registration_path  %></li>
          <li><%= link_to 'Helpful Links', links_index_path  %></li>
         <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>

        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Progress App</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <!-- Google font import! -->
 <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "layouts/navigation" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

 <!-- Render main -->

<body class="text-center">

<%= render "layouts/jumbotron" %>

    <%= yield %>
  </div>
<%= render "layouts/footer" %>
    </div>

</body>
</html>

app/views/links/index.html.erb
<div id="links">
<h1>Some helpful links</h1>
  <div class="links">
    <ul>
      <li><a href="https://www.psychologytoday.com/us/therapists">Psychology Today - Find a Therapist</a></li>
      <li><a href="https://www.nimh.nih.gov/labs-at-nimh/research-areas/clinics-and-labs/geb-sdge/mental-health-links.shtml">National Institute of Mental Health Links</a></li>
      <li><a href="https://www.nasmhpd.org/content/mental-health-links">National Association of State Mental Health Program Directors</a></li>
    </ul>
  </div>

</div>

app/views/users/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>